# Generated by Django 5.1.6 on 2025-04-09 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('director', models.CharField(max_length=255, verbose_name='Director')),
                ('description', models.TextField(verbose_name='Description')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration (minutes)')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('rating', models.FloatField(default=0.0, verbose_name='Rating')),
                ('release_year', models.PositiveIntegerField(verbose_name='Release Year')),
                ('popularity', models.IntegerField(default=0, verbose_name='Popularity')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='List Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
                ('movies', models.ManyToManyField(related_name='lists', to='app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Review Text')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
