# Generated by Django 5.1.6 on 2025-05-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
