# Generated by Django 5.1.6 on 2025-05-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, help_text='Ссылка на постер (URL). Например: https://image.tmdb.org/t/p/w500/abc.jpg', max_length=500),
        ),
    ]
